name: baby-1l-run-6
channels:
  - conda-forge
dependencies:
  - python
  - openmc # add version tag
  - openmc-plotter
  - numpy # add version tag
  - scipy # add version tag
  - matplotlib # add version tag
  - sympy
  - pandas
  - pint-pandas
  - nbconvert
  - ipykernel
  - pint
  - pip
  - pip:
      - git+https://github.com/libra-project/libra-toolbox@8644e0a62ebbbcc5def3401954bc8ab1ff91e734 # add version tag
      - openmc_data_downloader
      - matplotlib-label-lines
      - h-transport-materials
